version: 2
updates:
  - directory: /
    package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
      time: '04:00'
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
  - directory: /server
    package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
      time: '04:00'
    ignore:
      - dependency-name: 'cypress'
        update-types: ['version-update:semver-major']
      - dependency-name: 'cypress-localstorage-commands'
        update-types: ['version-update:semver-major']
